version: '3.0'
services:
  APP_CONTAINER_NAME:
    container_name: APP_CONTAINER_NAME
    build: .
    image: APP_CONTAINER_NAME
    working_dir: /home/node/app
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:TRAEFIK_ENV.chas.school"
    volumes:
      - ./:/home/node/app
    env_file:
      - .env
