version: '3.5'
services:
  react_client:
    container_name: react_client
    build: .
    image: react_client
    working_dir: /home/node/app
    labels:
      traefik.backend: "react_client"
      traefik.docker.network: "host"
      traefik.frontend.rule: "Host:client.chas.school"
    volumes:
      - ./:/home/node/app
    env_file:
      - .env
