FROM mhart/alpine-node:9.11.1 as app-builder

ADD yarn.lock /yarn.lock
ADD package.json /package.json

ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin

WORKDIR /app
COPY . /app

RUN yarn --ignore-engines

RUN yarn run build-css
RUN yarn run build

FROM nginx:latest
COPY --from=app-builder /app/build /usr/share/nginx/html

EXPOSE 80